### ISSUE TITLE
Error in building emacs from master repo: `news` and `wut` are not git commands

### ISSUE THREAD

**Issue by zenny** [cadadr/configuration#7]
@cadadr I came quite exited about your script to build emacs from the master repo from your reddit post at https://www.reddit.com/r/emacs/comments/gy24n5/compelling_reasons_to_use_emacs_27_or_28_right_now/ft95bp4/ . Thanks for posting.

However, when I tried to build, there are two git commands which is not found in git installed in voidlinux (I think it could be universal in any git from distro package manager).

```
$ ./build-emacs-master.sh
News since HEAD:
git: 'news' is not a git command. See 'git --help'.

The most similar command is
        notes
```

I replaced the `git news` with `git notes`, and the script again:

```
$ ./build-emacs-master.sh
News since HEAD:

Commits since HEAD:
git: 'wut' is not a git command. See 'git --help'.

The most similar commands are
        init
        jump
        pull
        push
        status
        switch
```

Would you mind explaining the origins of the two git commands viz. `news` and `wut`?

Cheers, and stay safe,
/z

**Comment by cadadr** [comment]
Oops.. those are aliases. Should've checked before sharing, those are a couple git aliases from my gitconfig. Pushing a commit that fixes it. Sorry for the let down. Thanks for the report!

**Comment by zenny** [comment]
@cadadr So nice of you for the prompt reply.

However, your update fixed the issue. However, even running the command from the same directory where `configure-emacs.sh` exists, the script still reports that specific file missing:

```
$ ./build-emacs-master_custom.sh
News since HEAD:

Commits since HEAD:
Continue with build (RETURN to continue, ^C to quit)?

warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.
./build-emacs-master_custom.sh: 24: configure-emacs.sh: not found
$ ls
64clip.sh                           build-emacs-master_custom.sh  elisp-byte-compile.sh  ffprofile.sh  gk-open-project.bash  invade      nnml2mbox.py   splitmbox.py
build-emacs-master.sh               configure-emacs.sh            elisp-lint.sh          fig.pl        gk-ssh-add.sh         journal.sh  passmenu.sh    unswap
build-emacs-master.sh_with_aliases  doi2bib.pl                    emacs-load-test.bash   git-clonex    gopher.sh             mp42gif.sh  run-python.sh  ydl-parallel.sh
```

Hmmm.. it does not seem a cross linking issue, imo?!

Cheers,

**Comment by cadadr** [comment]
No problem!

Can you try replacing the line that goes "TK=gtk3 ..." with `TK=gtk3 sh "$(dirname $0)/configure-emacs.sh"`?

Also, what `configure-emacs.sh` does is it runs the `./configure` script of emacs with some arguments that I like to use. If you want, you can replace that whole line with a direct call to `./configure --prefix=/some/dir ...` with flags and directories you like to use.  For my build setup it'd be 

```sh
# Generate ./configure script if missing
if [ ! -f configure ]; then
    ./autogen.sh all
fi

# Configure build
./configure \
    --prefix=$HOME/local/emacs \
    --with-x-toolkit=$TK \
    --with-modules \
    --with-file-notification=yes \
    --with-gameuser=no \
    --with-cairo \
    --with-mailutils \
    --with-imagemagick ;;
```

The cause of the error is that the script expects the `bin/` subdirectory in the path. I symlink that dir to `~/bin` on my system.

Do tell me if it works or not with the line.

**Comment by cadadr** [comment]
BTW same goes with `emacs-load-test.sh`.  You can replace that line with `EMACS=./src/emacs bash "$(dirname $0)/emacs-load-test.bash"`, or just `./src/emacs`. In the latter case it'll just run the newly compiled emacs, and will continue after when you quit out of it.

**Comment by zenny** [comment]
With `EMACS=./src/emacs bash "$(dirname $0)/emacs-load-test.bash"`

```
$ ./build-emacs-master_custom.sh
remote: Counting objects: 21, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 21 (delta 17), reused 0 (delta 0)
Unpacking objects: 100% (21/21), 3.78 KiB | 124.00 KiB/s, done.
From https://git.savannah.gnu.org/git/emacs
   dd939d7484..a6cc16d04c  feature/native-comp -> origin/feature/native-comp
News since HEAD:

Commits since HEAD:
Continue with build (RETURN to continue, ^C to quit)?

Already up to date.
sh: 0: Can't open ./configure-emacs.sh
```
With just `./src/emacs`, could not find the emacs-load-test script:

```
$ ./build-emacs-master_custom.sh
News since HEAD:

Commits since HEAD:
Continue with build (RETURN to continue, ^C to quit)?

Already up to date.
sh: 0: Can't open ./configure-emacs.sh
```
??

**Comment by cadadr** [comment]
Try this version:

```
#!/bin/sh
# build-emacs-master.sh --- fetch, review, merge and build Emacs master branch.

# This script is for pulling and building Emacs master branch
# interactively.  It depends on the ‘configure-emacs.sh’ and
# ‘emacs-load-test.bash’ scripts that reside in this same directory.
# Ideally, you should download these three scripts together and put
# them in to some directory which is in the $PATH.  Or, you can read
# the comments found inline which should help make it work without
# those scripts.

set -e

# Path to emacs git repo clone
cd ~/co/External/emacs

git branch | grep '^\* master' >/dev/null || exit 'Not on branch master!'

git fetch

echo News since HEAD:
git diff HEAD..FETCH_HEAD -- etc/NEWS

echo
echo Commits since HEAD:
git log --graph --oneline HEAD..FETCH_HEAD

echo 'Continue with build (RETURN to continue, ^C to quit)?'; read nought

git pull --ff-only
git clean -dfx

if [ ! -f configure ]; then
    ./autogen.sh all
fi
./configure --prefix=$HOME/local/emacs

make -j$(lscpu | awk '/^CPU\(s\):/ {print $2}')

echo Build finished, hit RETURN to continue to testing w/ -Q.; read nought
./src/emacs -Q

# Test if the compiled Emacs can load init.el.  The
# ‘emacs-load-test.sh’ should be in the PATH.  You can change the
# script file name, or just run ‘./src/emacs’ and ‘C-x C-c’ out of it
# if the config loads fine.
echo Hit RETURN to test w/ configuration.; read nought
./src/emacs

echo Hit RETURN to install...; read nought
mv ~/local/emacs ~/local/emacs.old && make install
```

**Comment by zenny** [comment]
UPDATE: I have copied both of your scripts related to emacs compilation to the src repo. The configuration script `TK=gtk3 ./configure-emacs.sh` went well, but  `make -j$(lscpu | awk '/^CPU\(s\):/ {print $2}')` produced the following error:

```
make[2]: Entering directory '~/Downloads/emacs-build/lisp'
  ELC      cedet/semantic/db-ref.elc
  ELC      cedet/semantic/format.elc
  ELC      cedet/semantic/fw.elc
  ELC      cedet/semantic/grammar-wy.elc
  ELC      cedet/semantic/grammar.elc
  ELC      cedet/semantic/html.elc
  ELC      cedet/semantic/ia-sb.elc
  ELC      cedet/semantic/ia.elc
  ELC      cedet/semantic/idle.elc
  ELC      cedet/semantic/imenu.elc
  ELC      cedet/semantic/java.elc
  ELC      cedet/semantic/lex-spp.elc
Bus error
make[2]: *** [Makefile:296: cedet/semantic/imenu.elc] Error 135
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '~Downloads/emacs-build/lisp'
make[1]: *** [Makefile:319: compile-main] Error 2
make[1]: Leaving directory '~/Downloads/emacs-build/lisp'
make: *** [Makefile:411: lisp] Error 2
```

The relevant files seems to exist in the emacs source repo:

```
$ find ./* -name db-ref.elc
./lisp/cedet/semantic/db-ref.elc
```

`Bus error` is something that does not say a thing. Fyi, I am on voidlinux which has no systemd.

Thanks!

**Comment by zenny** [comment]
UPDATE: I manually tried to configure without extra parameters, yet specifying just the prefix, it went well except a minor warning:

```
configure: WARNING: This configuration installs a 'movemail' program
that does not retrieve POP3 email.  By default, Emacs 25 and earlier
installed a 'movemail' program that retrieved POP3 email via only
insecure channels, a practice that is no longer recommended but that
you can continue to support by using './configure --with-pop'.
configure: You might want to install GNU Mailutils
<https://mailutils.org> and use './configure --with-mailutils'.
```

Continued with make and went without glitches, ran `./src/emacs -Q`  which successfully launched emacs in gtk mode. `EMACS=./src/emacs bash emacs-load-test.bash` also went OK.

```
]$ EMACS=./src/emacs bash emacs-load-test.bash
Loading /home/zenny/.emacs.d/init.el (source)...
Package cl is deprecated
Key Chord mode on
[yas] Prepared just-in-time loading of snippets successfully.
[yas] Prepared just-in-time loading of snippets successfully.
[yas] Prepared just-in-time loading of snippets successfully.
-OK-
Startup took 5.861258 seconds...
```

**Comment by zenny** [comment]
> Try this version:
> 
> ```
> #!/bin/sh
> # build-emacs-master.sh --- fetch, review, merge and build Emacs master branch.
> 
> # This script is for pulling and building Emacs master branch
> # interactively.  It depends on the ‘configure-emacs.sh’ and
> # ‘emacs-load-test.bash’ scripts that reside in this same directory.
> # Ideally, you should download these three scripts together and put
> # them in to some directory which is in the $PATH.  Or, you can read
> # the comments found inline which should help make it work without
> # those scripts.
> 
> set -e
> 
> # Path to emacs git repo clone
> cd ~/co/External/emacs
> 
> git branch | grep '^\* master' >/dev/null || exit 'Not on branch master!'
> 
> git fetch
> 
> echo News since HEAD:
> git diff HEAD..FETCH_HEAD -- etc/NEWS
> 
> echo
> echo Commits since HEAD:
> git log --graph --oneline HEAD..FETCH_HEAD
> 
> echo 'Continue with build (RETURN to continue, ^C to quit)?'; read nought
> 
> git pull --ff-only
> git clean -dfx
> 
> if [ ! -f configure ]; then
>     ./autogen.sh all
> fi
> ./configure --prefix=$HOME/local/emacs
> 
> make -j$(lscpu | awk '/^CPU\(s\):/ {print $2}')
> 
> echo Build finished, hit RETURN to continue to testing w/ -Q.; read nought
> ./src/emacs -Q
> 
> # Test if the compiled Emacs can load init.el.  The
> # ‘emacs-load-test.sh’ should be in the PATH.  You can change the
> # script file name, or just run ‘./src/emacs’ and ‘C-x C-c’ out of it
> # if the config loads fine.
> echo Hit RETURN to test w/ configuration.; read nought
> ./src/emacs
> 
> echo Hit RETURN to install...; read nought
> mv ~/local/emacs ~/local/emacs.old && make install
> ```

I oversighted the above. Apology.

**Comment by cadadr** [comment]
No problem, glad it's working for you now!
